name: Core

on:
  workflow_dispatch:
    inputs:
      # 保留输入参数，但不再使用
      post_telegram:
        description: 'Post to Telegram'
        required: true
        type: boolean
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Write key
        if: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/master') || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo androidStoreFile='key.jks' >> gradle.properties
            echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

      - name: Checkout libxposed/api
        uses: actions/checkout@v3
        with:
          repository: libxposed/api
          path: libxposed/api

      - name: Checkout libxposed/service
        uses: actions/checkout@v3
        with:
          repository: libxposed/service
          path: libxposed/service

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Build dependencies
        working-directory: libxposed
        run: |
          echo 'org.gradle.caching=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.parallel=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC' >> ~/.gradle/gradle.properties
          echo 'android.native.buildOutput=verbose' >> ~/.gradle/gradle.properties
          cd api
          ./gradlew publishToMavenLocal
          cd ../service
          ./gradlew publishToMavenLocal

      - name: Build with Gradle
        run: |
          ./gradlew zipAll

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          # 使用更健壮的文件名解析（避免空格和特殊字符问题）
          riruReleaseName=$(ls magisk-loader/release/LSPosed-v*-riru-release.zip 2>/dev/null | awk -F '[/_.-]' '{print $3"_"$4"_"$5}')
          riruDebugName=$(ls magisk-loader/release/LSPosed-v*-riru-debug.zip 2>/dev/null | awk -F '[/_.-]' '{print $3"_"$4"_"$5}')
          zygiskReleaseName=$(ls magisk-loader/release/LSPosed-v*-zygisk-release.zip 2>/dev/null | awk -F '[/_.-]' '{print $3"_"$4"_"$5}')
          zygiskDebugName=$(ls magisk-loader/release/LSPosed-v*-zygisk-debug.zip 2>/dev/null | awk -F '[/_.-]' '{print $3"_"$4"_"$5}')
          
          echo "riruReleaseName=$riruReleaseName" >> "$GITHUB_OUTPUT"
          echo "riruDebugName=$riruDebugName" >> "$GITHUB_OUTPUT"
          echo "zygiskReleaseName=$zygiskReleaseName" >> "$GITHUB_OUTPUT"
          echo "zygiskDebugName=$zygiskDebugName" >> "$GITHUB_OUTPUT"
          
          # 确保解压目录存在
          mkdir -p LSPosed-riru-release LSPosed-riru-debug LSPosed-zygisk-release LSPosed-zygisk-debug
          unzip -q magisk-loader/release/LSPosed-v*-riru-release.zip -d LSPosed-riru-release || true
          unzip -q magisk-loader/release/LSPosed-v*-riru-debug.zip -d LSPosed-riru-debug || true
          unzip -q magisk-loader/release/LSPosed-v*-zygisk-release.zip -d LSPosed-zygisk-release || true
          unzip -q magisk-loader/release/LSPosed-v*-zygisk-debug.zip -d LSPosed-zygisk-debug || true

      # 修复 upload-artifact 错误：指定具体版本号，避免 GitHub 解析问题
      - name: Upload riru release
        uses: actions/upload-artifact@v3.1.4
        with:
          name: ${{ steps.prepareArtifact.outputs.riruReleaseName }}
          path: "./LSPosed-riru-release/*"
          if-no-files-found: warn  # 避免因文件不存在导致失败

      - name: Upload riru debug
        uses: actions/upload-artifact@v3.1.4
        with:
          name: ${{ steps.prepareArtifact.outputs.riruDebugName }}
          path: "./LSPosed-riru-debug/*"
          if-no-files-found: warn

      - name: Upload zygisk release
        uses: actions/upload-artifact@v3.1.4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
          path: "./LSPosed-zygisk-release/*"
          if-no-files-found: warn

      - name: Upload zygisk debug
        uses: actions/upload-artifact@v3.1.4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
          path: "./LSPosed-zygisk-debug/*"
          if-no-files-found: warn

      - name: Upload mappings
        uses: actions/upload-artifact@v3.1.4
        with:
          name: mappings
          path: |
            magisk-loader/build/outputs/mapping
            app/build/outputs/mapping
          if-no-files-found: warn

      - name: Upload symbols
        uses: actions/upload-artifact@v3.1.4
        with:
          name: symbols
          path: build/symbols
          if-no-files-found: warn

      # 完全移除 Telegram 通知步骤
      # - name: Post to channel
      #   ...（已删除）
